### PR TITLE
Added functions for finding best fit rascal solutions

### PR DESCRIPTION
**Pull request by dingma0**

### CODE REVIEW

**Review by brandenjlynch — COMMENTED** [review]
Looks good overall -- I suggest we include at least one test case. Testing `FindBestFitSolutions` would make the most sense, as it makes use of all the key functions added here and represents an overall functional test for Rascal. We can use the bundled example data as a test case, but I suggest we bundle the correct test output (i.e., the rascal solutions and/or scaled copy-numbers) in the `tests/testthat/fixtures` directory.

**Comment by genomaxx** [comment]
A few points:
- I agree with Branden re: a test being needed, many functions can be tested at once with this way. I'll add though that it might make sense for said test to then run once for say 'mad' based scaling. 
- Something I realized while reading this PR is that with these new rascal functions we now have a whole group dedicated to rCN to aCN-scaling. I think it makes sense pull these out of utils.R and place them in the new cnscaling.R file.

**Comment by genomaxx** [comment]
Latest commits look alright.

**Comment by genomaxx** [comment]
Does the bugfix in [4496525](https://github.com/Huntsmanlab/utanos/pull/66/commits/44965253ae3895f1801c86dd8958c384c416deff) referring to the row count apply to the number of chromosomes? 23 seems like a very random arbitrary number for an index (same goes for 26 a bit later). If so, 23 is not robust for other references (eg. mouse)
Maybe there's a reasonable explanation I don't remember at the moment. Just want to double check.

**Comment by dingma0** [comment]
On another look I think we're not actually using the entire stats file, only the read counts line? So I just read the lines in and grep'd for that line.

**Comment by genomaxx** [comment]
Ah ok, ya thats a better solution.

**Comment by genomaxx** [comment]
Ok, a summary of what is in this PR (I think):
- [ ] Adding rascal functions needed
- [ ] Pulling CN calling functions out of utils into their own file (copynumberscaling.R) with the rascal functions
- [ ] Added roxygen docs for the new functions
- [ ] Test cases
- [ ] Modify the CN-Diversity vignette and demonstrate finding rascal solutions. (there is an empty section waiting for this bit)

**Comment by genomaxx** [comment]
Test looks good.
The difficulty in testing the GenKploidy function alongside this MAD-based test would be very trivial. 
But maybe given the difference in user situations that should be a distinct testthat call.

**Comment by dingma0** [comment]
nothing else related to rascal remains in the quickstart vignette

**Comment by dingma0** [comment]
reopening this one

**Pull request closed without merging**
